image: Visual Studio 2017
before_build:
  - nuget sources add -Name docfx-dev -Source https://www.myget.org/F/docfx-dev/api/v2
  - nuget restore

configuration:
  - Release

build:
  project: RestApi.sln

artifacts:
  - path: RestProcessor\bin\$(configuration)
    name: RestProcessorArtifacts
    type: zip
